open virus
[start Warning message]
{start last Warning message}
(click okay message)
{windows Security come's with a message}
{start tom and jerry}
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
(tom come's up computer)
(jerry come's up computer)
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
[Warning message you're computer is dead]
end:

